apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  labels:
    app: argocd-server
    environment: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: argocd-helm/charts/argo-cd
    repoURL: git@github.com:JoeX2/buttonCreator.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
