apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: default
  labels:
    app: ingress
    environment: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    helm:
      valueFiles:
      - argocd-helm/charts/helm/apps/ingress/values.yaml
    repoURL: git@github.com:JoeX2/buttonCreator.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
