apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
  labels:
    app: mariadb
    environment: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: mariadb
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 11.5.3
      chart: mariadb
      helm:
        valueFiles:
          - $values/argocd-helm/charts/helm/apps/mariadb/local-values.yaml
    - repoURL: git@github.com:JoeX2/buttonCreator.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
