ingress:
  ingressClass: traefik
  oauth2_proxy: []
  without_proxy:
    button-creator:
      button-creator:
        domainName: button-creator.joex2.dk
    argocd:
      argo-cd-argocd-server:
        domainName: argocd.joex2.dk
        subPath:
          argo-cd-argocd-dex-server:
            path: /dex
            port: 5557
certificate:
  certIssuer: letsencrypt
  kind: Issuer
