ingress:
  ingressClass: traefik
  oauth2_proxy: []
  without_proxy:
    button-creator:
      button-creator:
        domainName: button-creator-backend.joex2.dk
        port: 8080
      button-creator-webapp:
        domainName: new.joex2.dk
        port: 80
        subPath:
          button-creator:
            path: /backend/
            port: 8080
    argocd:
      argo-cd-argocd-server:
        domainName: argocd.joex2.dk
        subPath:
          argo-cd-argocd-dex-server:
            path: /dex
            port: 5557
certificate:
  certIssuer: letsencrypt
  kind: Issuer
