argo-cd:
  installCRDs: false
  dex:
    enabled: true
    livenessProbe:
      enabled: true
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      enabled: true
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
  controller:
    args:
      selfHealTimeout: "10"
      repoServerTimeoutSeconds: "180"
  server:
    extraArgs:
      - --insecure
    configEnabled: true
    config:
      url: https://argocd.joex2.dk
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: helm
          name: bitnami
          url: https://charts.bitnami.com/bitnami
        - url: git@github.com:JoeX2/buttonCreator.git
          sshPrivateKeySecret:
            name: ssh-key-secret
            key: github-privatekey
        - url: git@github.com:JoeX2/buttonCreator.git
          sshPrivateKeySecret:
            name: ssh-key-secret
            key: github-privatekey
      dex.config: |
        connectors:
        - config:
            issuer: https://accounts.google.com
            clientID: "857704499941-dk0rtk4e129rlscaln8agp5oajeu95n5.apps.googleusercontent.com"
            clientSecret: "4Er4beRcy-KvKzyHdH29rp-U"
          type: oidc
          id: google
          name: Google
    rbacConfig:
      policy.csv: |
        g, joe.sorensen@gmail.com, role:admin
      policy.default: role:readonly
      scopes: '[group, email]'
    rbacConfigCreate: true
