apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    run: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: http
  selector:
      run: "{{ .Chart.Name }}"
  sessionAffinity: None
  type: NodePort
