{{- $rootValues := .Values -}}
{{- range $namespaceName, $namespace := .Values.ingress.without_proxy }}
{{- $skip := "true" }}
{{- range $ingress, $val := $namespace }}
{{- if $val }}
{{- if $val.domainName }}
{{- $skip = "false" }}
{{- end }}
{{- end }}
{{- end }}
{{- if eq $skip "false" }}
---
apiVersion: cert-manager.io/v1
kind: Issuer 
metadata:
  name: {{ $rootValues.certificate.certIssuer }}
  namespace: {{ $namespaceName }}
  annotations:
    app.kubernetes.io/managed-by: "Helm"
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: jos@blue-ocean-robotics.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-private-key
    # Enable the HTTP-01 challenge provider
    solvers: 
    - http01:
        ingress:
          name: frontend
{{- end }}
{{- end }}

