replicaCount: 1

image:
  repository: flugdk/button-creator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

environment:
  dbhost: mariadb.mariadb.svc
  dbname: my_database
  dbuser: root
  dbpassword: 'OmEnIuZX5d'
